
USE [CAD_TRADE] 
GO

/****** Object:  StoredProcedure [dbo].[SP_USUARIOS_UP]    Script Date: 10/10/2019 14:52:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_USU_UPDATE]
(
	@USU_ID      INT,
	@USU_EMPRESA VARCHAR(50),
	@USU_USUARIO VARCHAR(50),
	@USU_STATUS  VARCHAR(50)
)
AS
BEGIN

	BEGIN TRY		
		BEGIN TRANSACTION
		UPDATE [dbo].[A_USUARIO]
		SET  [EMPRESA] = @USU_EMPRESA
			,[USUARIO] = @USU_USUARIO 
			,[STATUS]  = @USU_STATUS
		WHERE  ID = @USU_ID
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		SELECT 'ERRO AO ATUALIZAR O USUARIO!' AS RETORNO
		RETURN 0	
	END CATCH

	SELECT 'USUARIO ATUALIZADO COM SUCESSO !' AS RETORNO
	RETURN 0
END

GO