

USE CAD_TRADE 
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_USU_INSERT]
(
	@USU_EMPRESA VARCHAR(50),
	@USU_USUARIO VARCHAR(50),
	@USU_CPF     VARCHAR(11),
	@USU_STATUS  VARCHAR(50)
)
AS 
BEGIN

	IF EXISTS(SELECT * FROM A_USUARIO WHERE CPF = @USU_CPF AND ATIVO = 1)
	BEGIN
		SELECT 'JÁ EXISTE UM USUÁRIO CADASTRADO COM ESTE CPF! FAVOR VERIFICAR' AS RETORNO
		RETURN 0;			
	END

	BEGIN TRY
		BEGIN TRANSACTION
		INSERT INTO [dbo].[A_USUARIO] ( [EMPRESA],[USUARIO],[CPF],[STATUS] )
		VALUES ( @USU_EMPRESA ,@USU_USUARIO ,@USU_CPF ,@USU_STATUS )
		COMMIT TRANSACTION	
	END TRY  
	BEGIN CATCH  
		ROLLBACK TRANSACTION
		SELECT 'ERRO AO GRAVAR O USUÁRIO' AS RETORNO
		RETURN 0;
	END CATCH;
	
	SELECT 'USUARIO INCLUÍDO COM SUCESSO' AS RETORNO
	RETURN 0; 
END

GO
